<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Excursion;
use App\Models\Enterprise;

class ExcursionSeeder extends Seeder
{
    public function run(): void
    {
        $excursions = [
            [
                'name' => '½ J Brousse',
                'type' => 'adventure',
                'description' => 'Villages, école, brousse et retour des pêcheurs à Mbour.',
                'price_adult' => 21500,
                'price_child' => 11000,
                'duration_hours' => 4,
                'departure_time' => '08:30',
                'schedule_description' => 'Jours : Vendredi, Lundi, Jeudi, Samedi, Mardi (Matin 08h30-12h00 ou Après-midi 15h00-18h30).',
                'min_participants' => 4,
                'max_participants' => 20,
                'included' => ['Visite de villages & école', 'Retour des pêcheurs à Mbour', 'Repas & 1/2 eau inclus'],
                'not_included' => ['Boissons hors 1/2 eau', 'Dépenses personnelles'],
            ],
            [
                'name' => 'Joal - Fadiouth',
                'type' => 'cultural',
                'description' => 'Île aux coquillages, sécherie de poisson, balade traditionnelle en pirogue.',
                'price_adult' => 25000,
                'price_child' => 13000,
                'duration_hours' => 5,
                'departure_time' => '08:30',
                'schedule_description' => 'Jours : Dimanche, Mercredi, Jeudi, Vendredi (08h30 - 13h00).',
                'min_participants' => 2,
                'max_participants' => 25,
                'included' => ['Visite île aux coquillages', 'Sécherie de poisson', 'Balade en pirogue', 'Guide local'],
                'not_included' => ['Repas', 'Boissons'],
            ],
            [
                'name' => 'Réserve de Bandia',
                'type' => 'adventure',
                'description' => 'Safari animalier dans la réserve : girafes, antilopes, singes, rhinocéros, etc.',
                'price_adult' => 30000,
                'price_child' => 15000,
                'duration_hours' => 3,
                'departure_time' => '08:00',
                'schedule_description' => 'Jours : Vendredi, Dimanche, Lundi, Mardi, Jeudi, Samedi (Créneaux : 08h00-11h00 ou 08h30-11h30).',
                'min_participants' => 2,
                'max_participants' => 15,
                'included' => ['Safari animalier en camion 4x4', 'Entrée à la réserve', 'Guide spécialiste'],
                'not_included' => ['Déjeuner', 'Photos personnelles'],
            ],
            [
                'name' => 'Lac Rose',
                'type' => 'relaxation',
                'description' => 'Découverte du Lac Retba (Lac salé) et expérience de flottaison.',
                'price_adult' => 20000,
                'price_child' => 10000,
                'duration_hours' => 5,
                'departure_time' => '08:00',
                'schedule_description' => 'Jours : Vendredi (08h00 - 13h00).',
                'min_participants' => 2,
                'max_participants' => 20,
                'included' => ['Transport', 'Visite du Lac salé', 'Flottaison'],
                'not_included' => ['Repas', 'Balade en quad en option'],
            ],
            [
                'name' => 'Soirée Brousse',
                'type' => 'cultural',
                'description' => 'Lutte sérère traditionnelle, dîner typique et grand spectacle en brousse.',
                'price_adult' => 40000,
                'price_child' => 20000,
                'duration_hours' => 5,
                'departure_time' => '18:00',
                'schedule_description' => 'Jours : Mardi, Jeudi, Mercredi, Vendredi (Soirée brousse).',
                'min_participants' => 4,
                'max_participants' => 50,
                'included' => ['Dîner traditionnel', 'Spectacle de lutte sérère', 'Animations & Boissons incluses'],
                'not_included' => ['Achats personnels'],
            ],
            [
                'name' => 'Lagune Somone',
                'type' => 'relaxation',
                'description' => 'Balade en pirogue à la découverte de la lagune et de la réserve ornithologique des mangroves.',
                'price_adult' => 20000,
                'price_child' => 10000,
                'duration_hours' => 3,
                'departure_time' => '09:00',
                'schedule_description' => 'Jours : Dimanche, Jeudi (09h00 - 12h00).',
                'min_participants' => 2,
                'max_participants' => 20,
                'included' => ['Balade en pirogue', 'Guide naturaliste', 'Accès lagune & mangrove'],
                'not_included' => ['Repas', 'Boissons'],
            ],
            [
                'name' => 'Gorée / Lac Rose',
                'type' => 'cultural',
                'description' => 'Combiné sur une journée : Île historique de Gorée, musées et découverte du Lac Rose.',
                'price_adult' => 45000,
                'price_child' => 23000,
                'duration_hours' => 11,
                'departure_time' => '07:00',
                'schedule_description' => 'Jours : Mardi, Jeudi, Dimanche (07h00 - 18h00).',
                'min_participants' => 4,
                'max_participants' => 30,
                'included' => ['Traversée en chaloupe', 'Entrées musées Gorée', 'Visite Lac Rose', 'Déjeuner inclus'],
                'not_included' => ['Boissons personnelles'],
            ],
            [
                'name' => 'Dakar - Gorée',
                'type' => 'city_tour',
                'description' => 'Île historique de Gorée, musées, tour panoramique de la ville de Dakar et marchés artisanaux.',
                'price_adult' => 40000,
                'price_child' => 20000,
                'duration_hours' => 12,
                'departure_time' => '07:00',
                'schedule_description' => 'Jours : Dimanche, Mardi, Jeudi (07h00 - 19h00).',
                'min_participants' => 2,
                'max_participants' => 30,
                'included' => ['Traversée chaloupe Gorée', 'Visite guidée Dakar & musées', 'Déjeuner inclus'],
                'not_included' => ['Souvenirs personnels'],
            ],
            [
                'name' => 'Gorée en ½ Journée',
                'type' => 'cultural',
                'description' => 'Visite guidée de l\'île mémoire de Gorée et de ses musées.',
                'price_adult' => 28000,
                'price_child' => 14000,
                'duration_hours' => 4,
                'departure_time' => '07:00',
                'schedule_description' => 'Jours : Lundi, Jeudi, Vendredi, Dimanche (07h00-15h00 ou 08h00-13h00).',
                'min_participants' => 2,
                'max_participants' => 25,
                'included' => ['Traversée en chaloupe', 'Guide historique', 'Entrées musées'],
                'not_included' => ['Repas'],
            ],
            [
                'name' => 'Ranch aux Lions',
                'type' => 'adventure',
                'description' => 'Expérience exceptionnelle : marche encadrée très proche des lions en liberté.',
                'price_adult' => 35000,
                'price_child' => 20000,
                'duration_hours' => 4,
                'departure_time' => '08:00',
                'schedule_description' => 'Jours : Lundi, Jeudi, Vendredi, Dimanche (08h00 - 11h30 / 08h00 - 13h00).',
                'min_participants' => 2,
                'max_participants' => 15,
                'included' => ['Entrée ranch aux lions', 'Marche accompagnée par des rangers profs'],
                'not_included' => ['Repas', 'Photos pro'],
            ],
            [
                'name' => 'Bandia / Lions',
                'type' => 'adventure',
                'description' => 'Journée complète d\'aventure : Safari dans la Réserve de Bandia et marche au Ranch des Lions.',
                'price_adult' => 57500,
                'price_child' => 30000,
                'duration_hours' => 10,
                'departure_time' => '08:00',
                'schedule_description' => 'Jours : Samedi, Dimanche, Mercredi (08h00 - 18h00).',
                'min_participants' => 4,
                'max_participants' => 20,
                'included' => ['Safari réserve de Bandia', 'Entrée & marche ranch des lions', 'Déjeuner inclus'],
                'not_included' => ['Boissons'],
            ],
            [
                'name' => 'Saloum - Marlodj',
                'type' => 'adventure',
                'description' => 'Marché brousse, balade en pirogue dans les bolongs du Saloum, île aux oiseaux, village sérère et baobab.',
                'price_adult' => 38000,
                'price_child' => 19000,
                'duration_hours' => 10,
                'departure_time' => '08:00',
                'schedule_description' => 'Jours : Samedi, Dimanche, Mercredi (08h00 - 18h00).',
                'min_participants' => 4,
                'max_participants' => 25,
                'included' => ['Balade pirogue bolongs', 'Visite île de Marlodj & village', 'Repas & 1/2 eau inclus'],
                'not_included' => ['Boissons hors 1/2 eau'],
            ],
            [
                'name' => 'Lac Rose, Dunes & Plage',
                'type' => 'relaxation',
                'description' => 'Lac Retba salé, parcours des dunes de l\'étape finale du Paris-Dakar et détente sur la plage.',
                'price_adult' => 35000,
                'price_child' => 18000,
                'duration_hours' => 8,
                'departure_time' => '09:00',
                'schedule_description' => 'Jours : Mardi, Mercredi (09h00 - 17h00).',
                'min_participants' => 2,
                'max_participants' => 30,
                'included' => ['Visite Lac Rose & dunes', 'Accès plage', 'Déjeuner inclus'],
                'not_included' => ['Balade en quad en supplément'],
            ],
            [
                'name' => 'Somone / Oiseaux Exotiques',
                'type' => 'relaxation',
                'description' => 'Combiné balade en pirogue dans la mangrove de Somone et visite du parc des oiseaux exotiques.',
                'price_adult' => 35000,
                'price_child' => 18000,
                'duration_hours' => 4,
                'departure_time' => '09:00',
                'schedule_description' => 'Jours : Samedi, Lundi, Mardi, Jeudi, Vendredi (09h00 - 12h00 / 08h30 - 13h00).',
                'min_participants' => 2,
                'max_participants' => 25,
                'included' => ['Pirogue lagune Somone', 'Entrée parc oiseaux exotiques', 'Guide'],
                'not_included' => ['Repas'],
            ],
            [
                'name' => 'Marché Brousse ½ J',
                'type' => 'cultural',
                'description' => 'Immersion typique dans un marché local hebdomadaire de brousse.',
                'price_adult' => 20000,
                'price_child' => 10000,
                'duration_hours' => 4,
                'departure_time' => '08:30',
                'schedule_description' => 'Jours : Jeudi, Mercredi, Samedi (08h30 - 13h00).',
                'min_participants' => 2,
                'max_participants' => 20,
                'included' => ['Transport', 'Guide accompagnateur local'],
                'not_included' => ['Achats personnels'],
            ],
            [
                'name' => 'Journée Saint-Louis',
                'type' => 'cultural',
                'description' => 'Tour de la ville historique de Saint-Louis en calèche, musée de l\'Aéropostale et quartier des pêcheurs.',
                'price_adult' => 70000,
                'price_child' => 35000,
                'duration_hours' => 12,
                'departure_time' => '07:00',
                'schedule_description' => 'Jours : Lundi, Jeudi (07h00 - 19h00).',
                'min_participants' => 4,
                'max_participants' => 20,
                'included' => ['Tour de ville en calèche', 'Visite musée Aéropostale', 'Quartier des pêcheurs', 'Déjeuner inclus'],
                'not_included' => ['Boissons'],
            ],
            [
                'name' => '2 Jrs Désert Lompoul / St Louis',
                'type' => 'adventure',
                'description' => 'Nuit en bivouac sous tentes maures dans le désert de Lompoul, balade à dromadaire et visite de Saint-Louis.',
                'price_adult' => 110000,
                'price_child' => 55000,
                'duration_hours' => 29,
                'departure_time' => '13:30',
                'schedule_description' => 'Jours : Lundi, Jeudi (Départ 13h30 - Retour le lendemain 18h00). 2 Journées.',
                'min_participants' => 4,
                'max_participants' => 20,
                'included' => ['Bivouac désert Lompoul', 'Balade à dromadaire', 'Tentes maures', 'Repas inclus', 'Tour St-Louis'],
                'not_included' => ['Boissons hors repas'],
            ],
            [
                'name' => 'Parc Oiseaux Exotiques',
                'type' => 'relaxation',
                'description' => 'Visite guidée et observation d\'espèces d\'oiseaux exotiques rares.',
                'price_adult' => 20000,
                'price_child' => 10000,
                'duration_hours' => 2,
                'departure_time' => '09:00',
                'schedule_description' => 'Jours : Tous les jours (09h00 - 11h00).',
                'min_participants' => 1,
                'max_participants' => 30,
                'included' => ['Entrée au parc', 'Guide ornithologique'],
                'not_included' => ['Transport'],
            ],
            [
                'name' => 'Pêche en Mer',
                'type' => 'adventure',
                'description' => 'Session de pêche en mer artisanale tous les jours avec équipement complet.',
                'price_adult' => 20000,
                'price_child' => 10000,
                'duration_hours' => 4,
                'departure_time' => '08:00',
                'schedule_description' => 'Jours : Tous les jours (08h00 à 12h00 / 13h00). (30,50 euros / 20 000 FCFA par personne).',
                'min_participants' => 1,
                'max_participants' => 10,
                'included' => ['Matériel de pêche', 'Bateau & équipage'],
                'not_included' => ['Boissons'],
            ],
        ];

        $enterpriseIds = Enterprise::all()->pluck('id')->push(null);

        foreach ($enterpriseIds as $enterpriseId) {
            if ($enterpriseId === null) {
                Excursion::whereNull('enterprise_id')->delete();
            } else {
                Excursion::where('enterprise_id', $enterpriseId)->delete();
            }

            $order = 1;
            foreach ($excursions as $data) {
                Excursion::create([
                    'enterprise_id' => $enterpriseId,
                    'name' => ['fr' => $data['name'], 'en' => $data['name']],
                    'type' => $data['type'],
                    'description' => ['fr' => $data['description'], 'en' => $data['description']],
                    'price_adult' => $data['price_adult'],
                    'price_child' => $data['price_child'],
                    'duration_hours' => $data['duration_hours'],
                    'departure_time' => $data['departure_time'],
                    'schedule_description' => $data['schedule_description'],
                    'min_participants' => $data['min_participants'],
                    'max_participants' => $data['max_participants'],
                    'included' => $data['included'],
                    'not_included' => $data['not_included'],
                    'status' => 'available',
                    'is_featured' => $order <= 5,
                    'display_order' => $order++,
                    'is_active' => true,
                ]);
            }
        }
    }
}
