<?php

return [
    'Afghane', 'Albanaise', 'Algérienne', 'Allemande', 'Américaine', 'Andorrane', 'Angolaise',
    'Argentine', 'Arménienne', 'Australienne', 'Autrichienne', 'Azerbaïdjanaise', 'Bahreïnienne',
    'Bangladaise', 'Belge', 'Bélizienne', 'Béninoise', 'Bhoutanaise', 'Biélorusse', 'Birmane',
    'Bolivienne', 'Bosnienne', 'Botswanaise', 'Brésilienne', 'Britannique', 'Bruneienne', 'Bulgare',
    'Burkinabée', 'Burundaise', 'Cambodgienne', 'Camerounaise', 'Canadienne', 'Cap-verdienne',
    'Centrafricaine', 'Chilienne', 'Chinoise', 'Chypriote', 'Colombienne', 'Comorienne', 'Congolaise',
    'Coréenne', 'Costaricaine', 'Croate', 'Cubaine', 'Danoise', 'Djiboutienne', 'Dominicaine',
    'Dominiquaise', 'Égyptienne', 'Émirienne', 'Équatorienne', 'Érythréenne', 'Espagnole', 'Est-timoraise',
    'Estonienne', 'Éthiopienne', 'Fidjienne', 'Finlandaise', 'Française', 'Gabonaise', 'Gambienne',
    'Géorgienne', 'Ghanéenne', 'Grenadienne', 'Guatémaltèque', 'Guinéenne', 'Guinéenne (Équatoriale)',
    'Guyanienne', 'Haïtienne', 'Hondurienne', 'Hongroise', 'Indienne', 'Indonésienne', 'Irakienne',
    'Iranienne', 'Irlandaise', 'Islandaise', 'Israélienne', 'Italienne', 'Ivoirienne', 'Jamaïcaine',
    'Japonaise', 'Jordanienne', 'Kazakhe', 'Kényane', 'Kirghize', 'Kiribatienne', 'Koweïtienne',
    'Laotienne', 'Lésothienne', 'Lettone', 'Libanaise', 'Libérienne', 'Libyenne', 'Liechtensteinoise',
    'Lituanienne', 'Luxembourgeoise', 'Macédonienne', 'Malgache', 'Malaisienne', 'Malawienne',
    'Maldivienne', 'Malienne', 'Maltaise', 'Marocaine', 'Marshallaise', 'Mauricienne', 'Mauritanienne',
    'Mexicaine', 'Micronésienne', 'Moldave', 'Monégasque', 'Mongole', 'Monténégrine', 'Mozambicaine',
    'Namibienne', 'Nauruane', 'Népalaise', 'Nicaraguayenne', 'Nigériane', 'Nigérienne', 'Norvégienne',
    'Néo-zélandaise', 'Omanaise', 'Ougandaise', 'Ouzbèke', 'Pakistanaise', 'Palaoise', 'Palestinienne',
    'Panaméenne', 'Papouane-néo-guinéenne', 'Paraguayenne', 'Péruvienne', 'Philippine', 'Polonaise',
    'Portugaise', 'Qatarienne', 'Roumaine', 'Russe', 'Rwandaise', 'Saint-marinaise', 'Salvadorienne',
    'Samoane', 'Santoméenne', 'Saoudienne', 'Sénégalaise', 'Serbe', 'Seychelloise', 'Sierra-léonaise',
    'Singapourienne', 'Slovaque', 'Slovène', 'Somalienne', 'Soudanaise', 'Sud-africaine', 'Sud-coréenne',
    'Sudaise', 'Surinamaise', 'Swazie', 'Suédoise', 'Suisse', 'Syrienne', 'Tadzhike', 'Taïwanaise',
    'Tanzanienne', 'Tchadienne', 'Tchèque', 'Thaïlandaise', 'Togolaise', 'Tonguienne', 'Trinidadienne',
    'Tunisienne', 'Turkmène', 'Turque', 'Tuvaluane', 'Ukrainienne', 'Uruguayenne', 'Vanuataise',
    'Vénézuélienne', 'Vietnamienne', 'Yéménite', 'Zambienne', 'Zimbabwéenne',
];
